{"version":3,"file":"todo-not-found-exception.js","sourceRoot":"","sources":["todo-not-found-exception.ts"],"names":[],"mappings":";;AAAA,0DAAgE;AAChE,0DAAiD;AAGjD,MAAa,qBAAsB,SAAQ,kCAAoB;IAE3D,YAAmB,EAAU;QAEzB,mBAAK,CAAC,EAAE,EAAE,IAAI,CAAC,CAAC,cAAc,EAAE,CAAC,cAAc,EAAE,CAAC;QAElD,KAAK,CAAC,iBAAiB,EAAE,kBAAkB,CAAC,CAAC;IACjD,CAAC;CACJ;AARD,sDAQC","sourcesContent":["import { ApplicationException } from \"@nivinjoseph/n-exception\";\r\nimport { given } from \"@nivinjoseph/n-defensive\";\r\n\r\n\r\nexport class TodoNotFoundException extends ApplicationException\r\n{\r\n    public constructor(id: string)\r\n    {\r\n        given(id, \"id\").ensureHasValue().ensureIsString();\r\n        \r\n        super(`Todo with id '${id}' was not found.`);\r\n    }\r\n}\r\n"]}