{"version":3,"file":"todo-not-found-exception.js","sourceRoot":"","sources":["todo-not-found-exception.ts"],"names":[],"mappings":";;AAAA,0DAAgE;AAChE,0DAAiD;AAGjD,MAAa,qBAAsB,SAAQ,kCAAoB;IAE3D,YAAmB,EAAU;QAEzB,mBAAK,CAAC,EAAE,EAAE,IAAI,CAAC,CAAC,cAAc,EAAE,CAAC,cAAc,EAAE,CAAC;QAElD,KAAK,CAAC,iBAAiB,EAAE,kBAAkB,CAAC,CAAC;IACjD,CAAC;CACJ;AARD,sDAQC","sourcesContent":["import { ApplicationException } from \"@nivinjoseph/n-exception\";\nimport { given } from \"@nivinjoseph/n-defensive\";\n\n\nexport class TodoNotFoundException extends ApplicationException\n{\n    public constructor(id: string)\n    {\n        given(id, \"id\").ensureHasValue().ensureIsString();\n        \n        super(`Todo with id '${id}' was not found.`);\n    }\n}\n"]}